Sqlalchemy experiments
ydb-platform/ydb-python-sdk pull request #152
Opened 2023-02-14 16:31 UTC by Valeria1235

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Support ydb dialect for sqlalchemy. Work in progress.

## Pull request type

- [ ] Bugfix
- [*] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

Issue Number: [N/A](https://github.com/ydb-platform/ydb-python-sdk/issues/111)

2023-02-15 12:09 UTC, rekby requested changes
and need to pass tests

2023-02-15 14:49 UTC, Valeria1235 commented on ydb/_dbapi/__init__.py
> +version = "0.0.31"
I have no idea) will drop it

2023-02-15 15:06 UTC, Valeria1235 commented on ydb/_sqlalchemy/__init__.py
> +            raise dbapi.errors.NotSupportedError
this isn't necessary

2023-02-15 15:30 UTC, Valeria1235 commented on ydb/_dbapi/connection.py
> +        pass
no, sqlalchemy used it implicitly and there will raises on `engine.connect`

2023-02-15 15:39 UTC, Valeria1235 commented on ydb/_dbapi/connection.py
> +        return driver, ydb.SessionPool(driver)
i agree

2023-02-16 05:55 UTC, rekby approved these changes

2023-02-16 14:30 UTC, merged