can use datetime.date as param in execute
ydb-platform/ydb-python-sdk pull request #166
Opened 2023-02-20 16:33 UTC by Valeria1235

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Bugfix with passing datetime.date in params

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

Issue Number: https://github.com/ydb-platform/ydb-python-sdk/issues/163

2023-02-20 20:08 UTC, gridnevvvit approved these changes

2023-02-21 05:13 UTC, rekby approved these changes
great!

2023-02-21 08:03 UTC, rekby requested changes
need write change to CHANGELOG.md

2023-02-21 14:26 UTC, rekby approved these changes

2023-02-21 14:26 UTC, merged