Fix cancel logic during SessionPool.acquire()
ydb-platform/ydb-python-sdk pull request #537
Opened 2024-12-20 10:22 UTC by MBogda

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

In case of a cancel during `SessionPool.acquire()` is waiting for a free session, a sub-task is not canceled, so session is acquired and lost.

## What is the new behavior?

Sub-task `self._active_queue.get()` is cancelled in case of `asyncio.CancelledError` error during execution of `ydb.aio.table.SessionPool._get_session_from_queue()`.

## Other information

### Script to reproduce

You need to have a running YDB at `localhost:2135`.
Script will never stop because of the bug, so you need to stop it manually (e.g. hit `ctrl+C`).

```
import asyncio

import ydb

async def main():
    async with ydb.aio.Driver(endpoint="localhost:2135", database="/local") as driver:
        await driver.wait()
        pool = ydb.aio.SessionPool(driver, size=1)
        asyncio.create_task(log(pool))
        await asyncio.gather(first_connection(pool), second_connection(pool), third_connection(pool))
        print("End of execution")
        await asyncio.sleep(1)

async def first_connection(pool: ydb.aio.SessionPool):
    print("First session acquiring")
    session = await pool.acquire()
    print("First session acquired")
    await asyncio.sleep(5)
    print("First session releasing")
    await pool.release(session)
    print("First session released")

async def second_connection(pool: ydb.aio.SessionPool):
    await asyncio.sleep(1)
    print("Second session acquiring")
    try:
        session = await asyncio.wait_for(pool.acquire(), timeout=1)
        # will not be called because of TimeoutError
        print("Second session acquired")
        print("Second session releasing")
        await pool.release(session)
        print("Second session released")
    except asyncio.TimeoutError:
        print("Second session acquiring aborted")
    finally:
        print("Second function closed")

async def third_connection(pool: ydb.aio.SessionPool):
    await asyncio.sleep(2)
    print("Third session acquiring")
    session = await pool.acquire()
    print("Third session acquired")
    print("Third session releasing")
    await pool.release(session)
    print("Third session released")

async def log(pool):
    while True:
        print(f"Pool size {pool._active_queue.qsize()}/{pool._size} : Active count {pool._active_count}")
        await asyncio.sleep(0.5)

asyncio.run(main())
```

### Output before the changes

```
Pool size 0/1 : Active count 0
First session acquiring
First session acquired
Pool size 0/1 : Active count 1
Second session acquiring
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Third session acquiring
Second session acquiring aborted
Second function closed
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
First session releasing
First session released
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Traceback (most recent call last):
  File "/Users/ya-bogdan/.pyenv/versions/3.11.8/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ya-bogdan/.pyenv/versions/3.11.8/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/ya-bogdan/Library/Application Support/JetBrains/PyCharm2023.3/scratches/three_requests_pool.py", line 11, in main
    await asyncio.gather(first_connection(pool), second_connection(pool), third_connection(pool))
  File "/Users/ya-bogdan/Library/Application Support/JetBrains/PyCharm2023.3/scratches/three_requests_pool.py", line 45, in third_connection
    session = await pool.acquire()
              ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ya-bogdan/projects/ydb-python-sdk/ydb/aio/table.py", line 606, in acquire
    session = await self._get_session_from_queue(timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ya-bogdan/projects/ydb-python-sdk/ydb/aio/table.py", line 566, in _get_session_from_queue
    done, _ = await asyncio.wait((task_wait, task_should_stop), return_when=asyncio.FIRST_COMPLETED)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ya-bogdan/.pyenv/versions/3.11.8/lib/python3.11/asyncio/tasks.py", line 428, in wait
    return await _wait(fs, timeout, return_when, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ya-bogdan/.pyenv/versions/3.11.8/lib/python3.11/asyncio/tasks.py", line 535, in _wait
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ya-bogdan/Library/Application Support/JetBrains/PyCharm2023.3/scratches/three_requests_pool.py", line 58, in <module>
    asyncio.run(main())
  File "/Users/ya-bogdan/.pyenv/versions/3.11.8/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/ya-bogdan/.pyenv/versions/3.11.8/lib/python3.11/asyncio/runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt
```

### Output after the changes

```
Pool size 0/1 : Active count 0
First session acquiring
First session acquired
Pool size 0/1 : Active count 1
Second session acquiring
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Third session acquiring
Second session acquiring aborted
Second function closed
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
Pool size 0/1 : Active count 1
First session releasing
First session released
Third session acquired
Third session releasing
Third session released
End of execution
Pool size 1/1 : Active count 1
Pool size 1/1 : Active count 1
```

2024-12-20 15:52 UTC, vgvoleg requested changes
Hi! Can you please add a test?

2024-12-23 21:55 UTC, MBogda commented
> Hi! Can you please add a test?

Hi! I've modified existing test `test_no_race_after_future_cancel` so that it fails without changes and passes with them.

2024-12-27 09:45 UTC, MBogda commented
@vgvoleg hi! Can you please review it?

2025-01-08 16:59 UTC, makhalin commented on ydb/aio/table.py
> +            raise exc
**issue:** Just 
```suggestion
            raise
```

2025-01-10 11:33 UTC, MBogda commented on tests/aio/test_session_pool.py
> +    await asyncio.sleep(0.001)
@rekby hi! Could you check it please now? Thanks!

2025-01-13 12:04 UTC, MBogda commented on tests/aio/test_session_pool.py
> +    await asyncio.sleep(0.001)
@vgvoleg hi again, could you check the new version please? Thanks!

2025-01-13 12:55 UTC, merged